CREATE DATABASE VisionTechBD;
GO

USE VisionTechBD
GO

CREATE TABLE Categoria(
	IdCategoria VARCHAR(40) PRIMARY KEY NOT NULL,
	Nome VARCHAR(100) NOT NULL,
);
GO

CREATE TABLE Produto(
	IdProduto VARCHAR(40) PRIMARY KEY NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Imagem VARCHAR(100),
	IdCategoria VARCHAR(40) FOREIGN KEY REFERENCES Categoria(IdCategoria)
);
GO

CREATE TABLE Usuario(
	IdUsuario VARCHAR(40) PRIMARY KEY NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Senha VARCHAR(60) NOT NULL,
	Email VARCHAR(256) NOT NULL,
);


SELECT * FROM Usuario;

SELECT * FROM Produto;

